314Project/Models/Message.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace _314Project.Models
{
    public class Message
    {
        public int ID { get; set; }
        [Required]
        public string UserName { get; set; }
        [Required]
        public string Text { get; set; }
        public DateTime When { get; set; }
        public string UserID { get; set; }

        public virtual ApplicationUser Sender { get; set; }
        public Message()
        {
            When = DateTime.Now;
        }
    }
}

314Project/Controllers/InvitesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using _314Project.Data;
using _314Project.Models;

namespace _314Project.Controllers
{
    public class InvitesController : Controller
    {
        private readonly ApplicationDBContext _context;

        public List<SelectListItem> GetUsers()
        {
            var UserList = _context.ApplicationUser;
            var UserInfo = new List<SelectListItem>();//Array
            foreach (ApplicationUser u in UserList)//All User rows
            {
                UserInfo.Add(new SelectListItem
                {
                    Value = u.Id.ToString(),
                    Text = u.GameID + " " + u.GameTag

                });
            }
            return UserInfo;
        }

        public InvitesController(ApplicationDBContext context)
        {
            _context = context;
        }

        // GET: Invites
        public async Task<IActionResult> Index()
        {
            ViewBag.InviteList = new List<String>();
            ViewBag.InviteList2 = new List<String>();


            var invites = await _context.Invites.AsNoTracking().Include(e => e.User.Game).ToListAsync();

            //NOTE: this can contain duplicate strings added to `InviteList`, unless you 
            //include more data field in each item.
            foreach (Invite i in invites)
            {
                ViewBag.InviteList.Add(i.User.Game.GameName);
                ViewBag.InviteList2.Add(i.User.GameTag);

            }


            return View(await _context.Invites.ToListAsync());
        }

        // GET: Invites/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var invite = await _context.Invites
                .FirstOrDefaultAsync(m => m.ID == id);
            if (invite == null)
            {
                return NotFound();
            }

            return View(invite);
        }

        // GET: Invites/Create
        public IActionResult Create()
        {
            ViewBag.UsersID = GetUsers();
            return View();
        }

        // POST: Invites/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID")] Invite invite)
        {
            if (ModelState.IsValid)
            {
                _context.Add(invite);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(invite);
        }

        // GET: Invites/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var invite = await _context.Invites.FindAsync(id);
            if (invite == null)
            {
                return NotFound();
            }
            return View(invite);
        }

        // POST: Invites/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID")] Invite invite)
        {
            if (id != invite.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(invite);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InviteExists(invite.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(invite);
        }

        // GET: Invites/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var invite = await _context.Invites
                .FirstOrDefaultAsync(m => m.ID == id);
            if (invite == null)
            {
                return NotFound();
            }

            return View(invite);
        }

        // POST: Invites/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var invite = await _context.Invites.FindAsync(id);
            _context.Invites.Remove(invite);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InviteExists(int id)
        {
            return _context.Invites.Any(e => e.ID == id);
        }
    }
}

314Project/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using _314Project.Data;
using _314Project.Models;
using Microsoft.AspNetCore.Identity;

namespace _314Project.Controllers
{
    public class MessagesController : Controller
    {
        private readonly ApplicationDBContext _context;
        private readonly UserManager<ApplicationUser> _userManager;


        public MessagesController(ApplicationDBContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;

        }

        // GET: Messages
        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(User);

            if (User.Identity.IsAuthenticated)
            {
                ViewBag.CurrentUserName = currentUser.UserName;

            }

            var messages = await _context.Messages.ToListAsync();

            var applicationDBContext = _context.Messages.Include(m => m.Sender);

            return View(await applicationDBContext.ToListAsync());
        }

        // GET: Messages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var message = await _context.Messages
                .Include(m => m.Sender)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (message == null)
            {
                return NotFound();
            }

            return View(message);
        }

        // GET: Messages/Create
        public IActionResult Create()
        {
            ViewData["UserID"] = new SelectList(_context.ApplicationUser, "Id", "Id");
            return View();
        }

        // POST: Messages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,UserName,Text,When,UserID")] Message message)
        {
            if (ModelState.IsValid)
            {
                message.UserName = User.Identity.Name;
                var sender = await _userManager.GetUserAsync(User);
                message.UserID = sender.Id;
                await _context.Messages.AddAsync(message);

                //_context.Add(message);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }
            //ViewData["UserID"] = new SelectList(_context.ApplicationUser, "Id", "Id", message.UserID);
            return View(message);
        }

        // GET: Messages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var message = await _context.Messages.FindAsync(id);
            if (message == null)
            {
                return NotFound();
            }
            ViewData["UserID"] = new SelectList(_context.ApplicationUser, "Id", "Id", message.UserID);
            return View(message);
        }

        // POST: Messages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,UserName,Text,When,UserID")] Message message)
        {
            if (id != message.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(message);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MessageExists(message.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserID"] = new SelectList(_context.ApplicationUser, "Id", "Id", message.UserID);
            return View(message);
        }

        // GET: Messages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var message = await _context.Messages
                .Include(m => m.Sender)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (message == null)
            {
                return NotFound();
            }

            return View(message);
        }

        // POST: Messages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var message = await _context.Messages.FindAsync(id);
            _context.Messages.Remove(message);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MessageExists(int id)
        {
            return _context.Messages.Any(e => e.ID == id);
        }
    }
}

314Project/Controllers/SearchController.cs
using _314Project.Data;
using _314Project.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _314Project.Controllers
{
    public class SearchController : Controller
    {
        private readonly ApplicationDBContext _context;//Get database from DBcontext



        public SearchController(ApplicationDBContext context)
        {
            _context = context;
        }

        public IList<ApplicationUser> Movie { get; set; }
        [BindProperty(SupportsGet = true)]
        public string SearchString { get; set; }

        public IActionResult Index()
        {
            return View();
        }
        public async Task OnGetAsync()
        {
            var UserSearch = from p in _context.ApplicationUser
                             select p;
            if (!string.IsNullOrEmpty(SearchString))
            {
                UserSearch = UserSearch.Where(s => s.UserName.Contains(SearchString));
            }

            UserSearch = (IQueryable<ApplicationUser>)await UserSearch.ToListAsync();

        }
    }
}

314Project/Views/Messages/Create.cshtml
@model _314Project.Models.Message

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Message</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="When" class="control-label"></label>
                <input asp-for="When" class="form-control" />
                <span asp-validation-for="When" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserID" class="control-label"></label>
                <select asp-for="UserID" class ="form-control" asp-items="ViewBag.UserID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

314Project/Views/Messages/Delete.cshtml
@model _314Project.Models.Message

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Message</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.When)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.When)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sender.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

314Project/Views/Messages/Details.cshtml
@model _314Project.Models.Message

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Message</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.When)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.When)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sender.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

314Project/Views/Messages/Edit.cshtml
@model _314Project.Models.Message

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Message</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="When" class="control-label"></label>
                <input asp-for="When" class="form-control" />
                <span asp-validation-for="When" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserID" class="control-label"></label>
                <select asp-for="UserID" class="form-control" asp-items="ViewBag.UserID"></select>
                <span asp-validation-for="UserID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

314Project/Views/Messages/Index.cshtml
@model IEnumerable<_314Project.Models.Message>

@{
    ViewData["Title"] = "Index";
    var userName = User.Identity.Name;
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Fruitz</title>
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Fruitz</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="Messages" asp-action="">Public Chat</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="Search" asp-action="">Search (Working progress)</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="Invites" asp-action="">Invites (Working progress)</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">


        </main>
    </div>

    <div class="collapse navbar-collapse" id="navbarColor01">
        <h2 class="text-center text-primary">
            <i></i>&nbsp;Public Chat
        </h2>

        <div class="form-group row">
            <div class="col-md-12" id="chat">
                @if (Model != null)
                {
                    @foreach (var message in Model.OrderBy(m => m.When))
                    {
                        string containerClass, timePosition, textAlign, contcolor, offset;
                        if (userName == message.UserName)
                        {
                            containerClass = "container darker";
                            timePosition = "time-right text-light";
                            textAlign = "text-right text-white";
                            contcolor = "bg-primary";
                            offset = "col-md-6 offset-md-6";
                        }
                        else
                        {
                            containerClass = "container";
                            timePosition = "time-left";
                            textAlign = "time-left";
                            contcolor = "bg-light";
                            offset = "";
                        }
                        <div class="row">
                            <div class="@offset">
                                <div class="@containerClass @contcolor">
                                    <p class="sender @textAlign">@message.UserName</p>
                                    <p class="@textAlign">@message.Text</p>
                                    <span class="@timePosition">@message.When.ToString()</span>
                                </div>
                            </div>
                        </div>
                    }
                }
            </div>
            <div class="col-md-12">
                <form asp-action="Create"
                      data-ajax-begin="ClearInputField" data-ajax-complete=""
                      data-ajax-failure="alert('Fail)" data-ajax-success="SendMessage"
                      data-ajax="true" data-ajax-method="POST">

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <input name="Text" class="form-control-plaintext" id="messageText" />
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Send" id="SubmitButton" class="btn-primary" />
                    </div>
                    <input type="hidden" value="@userName" name="username" />
                </form>
            </div>
        </div>
    </div>
    @if (User.Identity.IsAuthenticated)
    {
        <script>
    const userName = "@ViewBag.CurrentUserName";
        </script>

    }



    <script scr="~/signalr/signalr.min.js"></script>
    <script scr="~/lib/jquery/dist/jquery.validate.unobtrusive-ajax.min.js"></script>
    <script scr="~/chat.js"></script>
    <script scr="~/js/signrReqHandler.js"></script>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - _314Project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>